### ISSUE TITLE
Async auth?

### ISSUE THREAD

**Issue by treefrog00** [logibit/Logibit.Hawk#7]
Are there any plans to allow CredsRepo to be async? Auth may require a lookup on a web service, database, etc...

The reference implementation of credentialsFunc takes a callback to execute once it has retrieved credentials, rather than expecting a standard function.

**Comment by haf** [comment]
Yes, that would be a good idea, indeed. The first versions have focused on correctness. If you PR async APIs, I'll merge them! :)
